@startuml Buhari Hotel Database

' question doesnt have a reference of customers
' also it doesnt state if a customer can order multiple main dishes.


' table
entity MainDish
entity SideDish
entity Dessert
entity Order
entity OrderItem

' relationship
Order ||--o{ OrderItem
OrderItem }o--o| MainDish
OrderItem }o--o| SideDish
OrderItem }o--o| Dessert

@enduml