@startuml Buhari Hotel ERD

' tables
entity Type {
  * id: INTEGER <<PK>>
  * name: VARCHAR(10)
}

entity MenuItem {
  * id: INTEGER <<PK>>
  * name: VARCHAR(100)
  * price: DECIMAL(10,2)
  * type_id: INTEGER <<FK>>
}

entity Order {
  * id: INTEGER <<PK>>
  * date: TIMESTAMP
  * total: DECIMAL(10,2)
}

entity OrderItem {
  * id: INTEGER <<PK>>
  * order_id: INTEGER <<FK>>
  * menu_id: INTEGER <<FK>>
  * quantity: INTEGER
  * price: DECIMAL(10,2)
}

Type ||--o{ MenuItem : "has"
Order ||--o{ OrderItem : "has"
MenuItem ||--o{ OrderItem : "has"

@enduml